name: Arron Gibson
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6167289682198316
title: Standing on the Ankles of Giants
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141213'
    - '#635a5b'
    - '#a59b9a'
    - '#e1dcd9'
  brandStrength: 0.4166426609735936
  lightness: 0.21114400192163885
  saturation: 0.8942716636229306
  rhythmicContrast: 0.5044300351291895
purpose: []
